services:
  - type: web
    name: thanawya-backend
    env: node
    plan: free
    buildCommand: npm install && npx puppeteer browsers install chrome
    startCommand: node backend/server.js
    envVars:
      - key: PORT
        value: 10000
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/.cache/puppeteer
